### ISSUE TITLE
How can I signal that my scene is ready to be displayed?

### ISSUE THREAD

**Issue by cosmin-novac** [MASSHUU12/godot-scene-loader#14]
The SceneLoader waits for the loading screen to be ready using "await loading_screen_instance.safe_to_load".
How can I similarly wait for the next_scene to be ready before loading it? I am doing some intensive calculations after the scene started that need a few seconds.

**Comment by MASSHUU12** [comment]
I understand you are asking if there is a possibility that, similar to loading screen, the scene loader waits until the loaded scene notifies that it is ready to be displayed?
Currently, this is not possible. Scene loader only checks the status of the loaded scene and if it has been loaded completely, it displays it. If I find a moment, I might implement this, as such a function would be interesting and, as we can see, useful.

 If I misunderstood the question, or you have other questions, I will be happy to answer them.

**Comment by cosmin-novac** [comment]
Hi. I added this functionality for myself, if you wish I could create a PR

**Comment by MASSHUU12** [comment]
Sure, feel free to open a PR
